extends:
  -  plugin:prettier/recommended
  -  react-app

plugins: 
  - jsx-a11y

env:
    browser: true
    commonjs: true
    es6: true
    node: true
    
parserOptions:
    ecmaFeatures:
        jsx: true
    sourceType: module

rules:
    valid-jsdoc: 2
    no-unused-vars: 2